Lesson 11
kokdot/testguru pull request #10
Opened 2021-03-05 07:53 UTC by kokdot

2021-03-05 08:14 UTC, BubuntuClu requested changes

2021-03-05 08:14 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `admin?`

2021-03-05 08:14 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
используй ассоциацию созданных тестов у пользователя, вместо костыля ниже

2021-03-05 08:14 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
в админке не нужен старт

2021-03-05 08:14 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if resource.class == Admin
тут тоже будет проверка через метод пользователя?

2021-03-05 08:14 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    elsif resource.class == User
зечем тут elsif? а если не отработает эта ветка?

2021-03-06 04:12 UTC, kokdot commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
есть

2021-03-06 04:14 UTC, kokdot commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
есть

2021-03-06 04:15 UTC, kokdot commented on app/controllers/admin/tests_controller.rb
> +  def start
есть

2021-03-06 04:19 UTC, kokdot commented on app/controllers/application_controller.rb
> +    elsif resource.class == User
есть

2021-03-06 04:19 UTC, kokdot commented on app/controllers/application_controller.rb
> +    if resource.class == Admin
есть

2021-03-06 07:50 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = current_user.tests.new(test_params)
Не эта ассоциация. Эта отвечает за пройденные тесты, а нужна ассоциация которая отвечает за созданные

2021-03-06 07:50 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.admin?
Можно использовать третичный оператор для сокращения строк
Условие ? Да : нет

2021-03-06 09:32 UTC, merged