Lesson 18
kokdot/testguru pull request #17
Opened 2021-03-27 13:28 UTC by kokdot

2021-03-27 19:53 UTC, BubuntuClu requested changes

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/bages_user.rb
> +  scope :bages_user, -> (user) { where(test_passage_id: TestPassage.where(user_id: user.id)) }
используй join при формировании подобных запросов

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :levels, -> (level) { where(level: level).pluck(:id) }
выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может выборка.

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :levels_user, -> (level) { where(test_success: true, user_id: current_user, test_id: Test.levels(level)).pluck(:test_id).uniq }
это похоже на методы, а не на скоупы. опять же про pluck тоже сюда относится. и про join в запросах

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      description = Condition.find(bages_rule.condition_id).description
у тебя же есть ассоциация на condition внутри badge_rule. зачем ты делаешь через find?

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    Test.find(test_id).title == description && TestPassage.test_attempt(test_id).count == 1
у тебя тестпассаж связн с тестом, ты тест можешь достать `test_passage.test`

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    TestPassage.categories_user(description) & Test.categories(description) == Test.categories(description)
много как-то операндов.
все тесты категорий сравнить со всеми тестами, которые проходил этот пользователь. получается всего 2. зачем пересечение брать и его сравнить с общим количеством?

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    TestPassage.levels_user(level) & Test.levels(level) == Test.levels(level)
и тут тоже много

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +
поправь оформление в файле. лишние пустые строки, либо наоборот отсутсвие пустых строк между методами

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def first_attempt?
не увидел использования этого метода. он еще актуален?

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/test_passage.rb
> +      save!
почему бэнг метод стал? если упадет сохранение то и приложение упадет. `!` добавил, а `rescue` блок нет. либо убрать надо, либо добавлять обработчик

2021-03-27 19:53 UTC, BubuntuClu commented on app/controllers/admin/bages_users_controller.rb
> +    @bages_users = BagesUser.bages_user
этот скоуп у тебя требует передачи пользователя как параметр

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/bages_rule.rb
> +  belongs_to :condition
мне кажется, это лишняя связь. можно сразу в правиле хранить значение для этого правила

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/bages_rule.rb
> +  belongs_to :condition
и старнно что правило принадлежит условию

2021-03-27 19:53 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  scope :test_attempt, -> (test_id) { where(test_success: true, user_id: current_user, test_id: test_id }
пользователя тоже через параметр надо передать. не всегда есть `current_user`

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      control = send("#{bages_rule.rule}_award?", description)
`bage_assign_to_user(bages_rule) if send("#{bages_rule.rule}_award?", description)`

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      control = send("#{bages_rule.rule}_award?", description)
вообще можно так организовать, что было бы красиво
`user.badges << badge if send("#{bages_rule.rule}_award?", description)`
но ты почему-то в BagesUser записываешь bages_rule, а не сам badge

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    BagesUser.create(test_passage_id: @test_passage, bages_rule_id: bages_rule)
называется BagesUser, а с пользователем никак не связано, пассаж и правило бейджа. надо какой-то другой нейминг

2021-03-27 19:53 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    BagesRules.all.each do |bages_rule|
мне кажется тут стоит делать перебор по существующим бейджам(Bage), а не по правилам. у тебя в бейдже  может быть несколько правил, в итоге делай перебор по правилам, ты можешь несколько раз выдать один и тот же бейж

2021-03-28 03:37 UTC, kokdot commented on app/models/bages_user.rb
> +  scope :bages_user, -> (user) { where(test_passage_id: TestPassage.where(user_id: user.id)) }
есть

2021-03-28 03:37 UTC, kokdot commented on app/models/test.rb
> +  scope :levels, -> (level) { where(level: level).pluck(:id) }
есть

2021-03-28 03:45 UTC, kokdot commented on app/models/test_passage.rb
> +  scope :levels_user, -> (level) { where(test_success: true, user_id: current_user, test_id: Test.levels(level)).pluck(:test_id).uniq }
есть

2021-03-28 03:47 UTC, kokdot commented on app/services/badge_service.rb
> +      description = Condition.find(bages_rule.condition_id).description
есть

2021-03-28 04:24 UTC, kokdot commented on app/services/badge_service.rb
> +    Test.find(test_id).title == description && TestPassage.test_attempt(test_id).count == 1
есть

2021-03-28 04:25 UTC, kokdot commented on app/models/test_passage.rb
> +  scope :test_attempt, -> (test_id) { where(test_success: true, user_id: current_user, test_id: test_id }
есть

2021-03-28 09:28 UTC, kokdot commented on app/services/badge_service.rb
> +    BagesRules.all.each do |bages_rule|
есть

2021-03-28 09:28 UTC, kokdot commented on app/services/badge_service.rb
> +    BagesUser.create(test_passage_id: @test_passage, bages_rule_id: bages_rule)
есть

2021-03-28 09:28 UTC, kokdot commented on app/services/badge_service.rb
> +      control = send("#{bages_rule.rule}_award?", description)
есть

2021-03-28 09:28 UTC, kokdot commented on app/models/test_passage.rb
> +  scope :test_attempt, -> (test_id) { where(test_success: true, user_id: current_user, test_id: test_id }
есть

2021-03-28 09:28 UTC, kokdot commented on app/models/bages_rule.rb
> +  belongs_to :condition
есть

2021-03-28 09:29 UTC, kokdot commented on app/services/badge_service.rb
> +    Test.find(test_id).title == description && TestPassage.test_attempt(test_id).count == 1
есть

2021-03-28 09:29 UTC, kokdot commented on app/services/badge_service.rb
> +      description = Condition.find(bages_rule.condition_id).description
есть

2021-03-28 09:29 UTC, kokdot commented on app/models/test_passage.rb
> +  scope :levels_user, -> (level) { where(test_success: true, user_id: current_user, test_id: Test.levels(level)).pluck(:test_id).uniq }
есть

2021-03-28 09:30 UTC, kokdot commented on app/models/test.rb
> +  scope :levels, -> (level) { where(level: level).pluck(:id) }
есть

2021-03-28 09:30 UTC, kokdot commented on app/models/bages_user.rb
> +  scope :bages_user, -> (user) { where(test_passage_id: TestPassage.where(user_id: user.id)) }
есть

2021-03-29 06:39 UTC, BubuntuClu requested changes

2021-03-29 06:39 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      byebug
это убьет приложение на проде. зависнет и все

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/bage.rb
> +    user.id == user.id
напомнило картинку 
![image](https://user-images.githubusercontent.com/13871063/112795556-5c596a00-9071-11eb-920d-cfcdfc7f2a2d.png)

нейминг плохой, не понятно что тут происходит

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def after_validation_check_success
это лучше проставлять в методе `update` у тест пассажа. ты там как раз определяешь закончился ли тест. а так добавляешь логику в колбэк, это не очень хорошо. сложно такое будет отслеживать

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    # if completed? && success?
комментарии надо убрат

2021-03-29 06:39 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    TestPassage.categories_user(description, @user) & category_ids == category_ids
количество операндов не поправил

2021-03-29 06:39 UTC, BubuntuClu commented on config/routes.rb
> +  # get 'bages_users/index'
это надо убрать

2021-03-29 06:39 UTC, BubuntuClu commented on db/migrate/20210325053915_create_rule_tests.rb
> +    create_table :rule_tests do |t|
а за что это таблица отвечает? почему не достаточно bages_rules?

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  # scope :levels_user, -> (level) { where(test_success: true, user_id: current_user, test_id: Test.levels(level)).pluck(:test_id).uniq }
удаляй сразу комменты

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    where(test_success: true, user_id: user.id, test_id: test_id).count
можно сделать скоуп на получение только пройденных тестов

2021-03-29 06:39 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    if completed? && success?
этот код дублируется еще и в валидации. надо либо вынести, либо как-то реорганизовать код. например вынести в контролле, чтобы в одном месте ставился этот флаг.

2021-03-29 06:39 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      return if bage.bage_of_user?(@user)
у тебя же многие-ко-многим связь между бейджем и пользователем должна быть,  так как каждый бейдж может получить каждый пользователь. а такая проверка тебе что дает?

2021-03-29 11:16 UTC, kokdot commented on app/services/badge_service.rb
> +    TestPassage.categories_user(description) & Test.categories(description) == Test.categories(description)
есть

2021-03-29 11:16 UTC, kokdot commented on app/services/badge_service.rb
> +    TestPassage.levels_user(level) & Test.levels(level) == Test.levels(level)
есть

2021-03-29 11:18 UTC, kokdot commented on app/models/test_passage.rb
> +  def first_attempt?
есть

2021-03-29 11:18 UTC, kokdot commented on app/models/test_passage.rb
> +      save!
есть

2021-03-29 11:19 UTC, kokdot commented on app/controllers/admin/bages_users_controller.rb
> +    @bages_users = BagesUser.bages_user
Я убрал это

2021-03-29 11:24 UTC, kokdot commented on app/models/bage.rb
> +    user.id == user.id
есть

2021-03-29 11:29 UTC, kokdot commented on app/models/test_passage.rb
> +  def after_validation_check_success
есть

2021-03-29 11:30 UTC, kokdot commented on app/models/test_passage.rb
> +    # if completed? && success?
есть

2021-03-29 11:30 UTC, kokdot commented on app/services/badge_service.rb
> +    TestPassage.categories_user(description, @user) & category_ids == category_ids
есть

2021-03-29 11:32 UTC, kokdot commented on app/models/test_passage.rb
> +  # scope :levels_user, -> (level) { where(test_success: true, user_id: current_user, test_id: Test.levels(level)).pluck(:test_id).uniq }
есть

2021-03-29 11:33 UTC, kokdot commented on app/models/test_passage.rb
> +    if completed? && success?
есть

2021-03-29 18:30 UTC, BubuntuClu approved these changes

2021-03-29 18:30 UTC, BubuntuClu commented on app/models/bage.rb
> +    user.id == owner.id
так. что тут user? ты удалил связь, теперь нет такой переменной/метода

2021-03-29 18:30 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +        bage_service = BageService.new(@test_passage, current_user)
пользователя можно из `@test_passage` достать. так будет на один аргумент меньше, что хорошо

2021-03-29 18:30 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    where(success_test: true, user_id: user.id, test_id: test_id).count
`success_test: true`
можно скоуп сделать. смотри сколько раз ты используешь эту опцию в запросах

2021-03-29 18:30 UTC, BubuntuClu commented on app/services/bage_service.rb
> +    Test.categories_ids(description) == TestPassage.categories_user(category_id, @user)
не уверен что надо выносить это в методы модели, так как там совсем специфичные запросы и врядли они будут где-то использоваться кроме этого сервиса. можно и тут сразу прописать полный текст запроса

2021-03-30 05:05 UTC, kokdot commented on app/services/badge_service.rb
> +      return if bage.bage_of_user?(@user)
есть

2021-03-30 05:05 UTC, kokdot commented on app/models/bage.rb
> +    user.id == owner.id
есть

2021-03-30 05:08 UTC, kokdot commented on app/controllers/test_passages_controller.rb
> +        bage_service = BageService.new(@test_passage, current_user)
есть

2021-03-30 05:16 UTC, kokdot commented on app/models/test_passage.rb
> +    where(success_test: true, user_id: user.id, test_id: test_id).count
есть

2021-03-30 05:37 UTC, kokdot commented on app/services/bage_service.rb
> +    Test.categories_ids(description) == TestPassage.categories_user(category_id, @user)
есть

2021-03-30 05:42 UTC, merged