lesson_18 dz2 0
kokdot/testguru pull request #18
Opened 2021-03-30 15:07 UTC by kokdot

2021-03-30 18:34 UTC, BubuntuClu requested changes

2021-03-30 18:34 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    if timer_is_over?
метод должен только принимать ответы. а ты тут уже луноход строишь. один метод отвечает за одно действие(принцип SOLID, буква S). а у тебя уже третье добавляется. вынеси лучше в test_passage#update. там у тебя есть проверки что делать если тест закончен, нужно только эту добавить

2021-03-30 18:34 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +      <p>Timer: <span class="seconds"><%= @test_passage.test.timer %></span></p>
таймера может не быть, тогда не надо рисовать таймер

2021-03-30 18:34 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    test.timer -= delta_time if delta_time < test.timer
что делает эта строчка?

2021-03-30 18:34 UTC, BubuntuClu commented on app/assets/javascripts/utilities/test_timer.js
> +  function timerDecrement() {
а где редирект?

2021-03-31 05:00 UTC, kokdot commented on app/models/test_passage.rb
> +    if timer_is_over?
есть

2021-03-31 05:01 UTC, kokdot commented on app/views/test_passages/show.html.erb
> +      <p>Timer: <span class="seconds"><%= @test_passage.test.timer %></span></p>
есть

2021-03-31 05:01 UTC, kokdot commented on app/models/test_passage.rb
> +    test.timer -= delta_time if delta_time < test.timer
есть

2021-03-31 05:01 UTC, kokdot commented on app/assets/javascripts/utilities/test_timer.js
> +  function timerDecrement() {
есть

2021-03-31 06:59 UTC, BubuntuClu requested changes

2021-03-31 06:59 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  # def current_question?
не нужный код удаляй, а не комментируй

2021-03-31 07:10 UTC, BubuntuClu requested changes

2021-03-31 07:10 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    redirect_to result_test_passage_path(@test_passage) and return if @test_passage.timer_is_over?
`and return` плохая конструкция, говорит о том что ты плохо продумал код.
и у тебя уже есть этот редирект в этом методе, заиспользуй его. ты не хочешь принять ответ пользователя?) вдруг он просто не успел кнопку нажать, а ответ выбрал. и это был последний вопрос, тогда и бейдж можно выдать

2021-03-31 07:10 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +      <% if @test_passage.test.timer > 0 %>
сделай хэлпер в test_passage вместо этого условия во вьюхе

2021-03-31 07:10 UTC, BubuntuClu commented on app/views/test_passages/show.html.erb
> +        <p>Timer: <span class="seconds"><%= @test_passage.test.timer - @test_passage.delta_time %></span></p>
это тоже на метод замени

2021-03-31 07:24 UTC, kokdot commented on app/models/test_passage.rb
> +  # def current_question?
есть

2021-03-31 07:24 UTC, kokdot commented on app/controllers/test_passages_controller.rb
> +    redirect_to result_test_passage_path(@test_passage) and return if @test_passage.timer_is_over?
есть

2021-03-31 07:36 UTC, BubuntuClu approved these changes

2021-03-31 07:36 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    # redirect_to result_test_passage_path(@test_passage) and return if @test_passage.timer_is_over?
только что выше было замечание про комменты и ты о5 оставляешь комментированный код)

2021-03-31 07:36 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +  def timer?
ну я вообще имел в виду методы модели, но в целом и так пойдет. я называю методы, которые возвращают true/false хэлпер методами, может это тебя смутило

2021-03-31 07:42 UTC, merged