lesson_4
kokdot/testguru pull request #3
Opened 2021-02-10 16:25 UTC by kokdot

2021-02-10 18:44 UTC, BubuntuClu requested changes

2021-02-10 18:44 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :users, :through => :user_tests
хэш-рокет(`=>`) это старый синтаксис, его стараемся не использовать уже

2021-02-10 18:44 UTC, BubuntuClu commented on app/models/test.rb
> +    where(category_id: Category.where(title: cat)).order(:title, :desc).pluck(:title)
у тебя тут выполняется два запроса, сначала поиск категории, а потом поиск тестов. ты уже знаешь про join. используй его тут чтобы сделать через 1 запрос

2021-02-10 18:44 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.cats(cat)
не надо ужиматься на имена методов и переменных. называть надо полностью и понятно, чтобы не надо было думать над расшифровкой. чем понятней код при беглом прочтении, тем лучше

2021-02-10 18:44 UTC, BubuntuClu commented on app/models/user.rb
> +    tests.where(level: level).count
почему `count`? просто тесты надо вернуть

2021-02-10 18:44 UTC, BubuntuClu commented on db/migrate/20210210145526_create_user_tests.rb
> +      t.references :user
внешний ключ надо добавить
`t.references :user, foreign_key: true`

2021-02-10 18:44 UTC, BubuntuClu commented on db/schema.rb
> +    t.boolean " ", default: false
тут что-то произошло. надо вернуть поле у ответов

2021-02-10 18:44 UTC, BubuntuClu commented on db/seeds.rb
> +question1 = Question.create(body: 'Чем отличается puts от print:', test_id: test.id)
если что можно в метод передать массив хэшей, тогда будет `Question.create([{...}, {...}])` и создатуться несколько объектов

2021-02-11 09:32 UTC, kokdot commented on app/models/test.rb
> +  has_many :users, :through => :user_tests
есть

2021-02-11 09:34 UTC, kokdot commented on app/models/test.rb
> +  def self.cats(cat)
есть

2021-02-11 09:35 UTC, kokdot commented on app/models/user.rb
> +    tests.where(level: level).count
есть

2021-02-11 09:39 UTC, kokdot commented on db/migrate/20210210145526_create_user_tests.rb
> +      t.references :user
есть

2021-02-11 09:59 UTC, kokdot commented on db/seeds.rb
> +question1 = Question.create(body: 'Чем отличается puts от print:', test_id: test.id)
есть

2021-02-11 10:56 UTC, kokdot commented on app/models/test.rb
> +    where(category_id: Category.where(title: cat)).order(:title, :desc).pluck(:title)
есть

2021-02-11 10:57 UTC, kokdot commented on app/models/test.rb
> +  def self.cats(cat)
есть

2021-02-11 10:57 UTC, kokdot commented on db/schema.rb
> +    t.boolean " ", default: false
есть

2021-02-13 10:19 UTC, merged