Lesson 5
kokdot/testguru pull request #4
Opened 2021-02-12 17:29 UTC by kokdot

2021-02-12 18:46 UTC, BubuntuClu requested changes

2021-02-12 18:46 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
в чем разница между `user` и `users`? один или много пользователей? без вникания в контекст не понятно. надо задать понятное название этой ассоциации

2021-02-12 18:46 UTC, BubuntuClu commented on db/migrate/20210209120259_add_references.rb
> +    add_reference :tests, :user, foreign_key: true
так делать нельзя. эта миграция уже слита в общий репозиторий(мастер ветка), нельзя задним числом править такие миграции, они не будут применены ни на сервер, ни у других разработчиков, а при обращении к новым полям будет возникать ошибка.

в таких случаях надо добавлять поля только через новую миграцию

2021-02-13 09:57 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: "User"
Работает эта ас

2021-02-13 10:22 UTC, kokdot commented on app/models/test.rb
> +  belongs_to :author, class_name: "User"
Сейчас заработала. Я с ней два дня бьюсь. добавил foreign_key

2021-02-14 06:52 UTC, merged