lesson_7
kokdot/testguru pull request #6
Opened 2021-02-17 16:03 UTC by kokdot

2021-02-17 18:44 UTC, BubuntuClu requested changes

2021-02-17 18:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end

2021-02-17 18:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test#, only: :index
тебе не во всех экшенах нужен тест

2021-02-17 18:44 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь опцию `shallow: true` у вопросов

2021-02-17 18:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    Question.find(params[:id]).destroy
а почему тут так ищешь вопрос, а в show `@test.questions.where(id: [params[:id]` таким образом?
надо придерживаться одного стиля. если метод поиска вопроса будет совпадать, то можно вынести это будет в колбэк.

2021-02-18 05:22 UTC, kokdot commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
есть

2021-02-18 05:26 UTC, kokdot commented on app/controllers/questions_controller.rb
> +  before_action :find_test#, only: :index
есть

2021-02-18 05:26 UTC, kokdot commented on config/routes.rb
> +    resources :questions
есть

2021-02-18 05:43 UTC, kokdot commented on app/controllers/questions_controller.rb
> +    Question.find(params[:id]).destroy
есть

2021-02-18 07:35 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_test, expect: [:destroy]
expect исключение пишется как except

2021-02-20 14:20 UTC, merged