Lesson 9
kokdot/testguru pull request #8
Opened 2021-02-26 19:02 UTC by kokdot

2021-02-26 19:45 UTC, BubuntuClu requested changes

2021-02-26 19:45 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай отве через ассоциацию вопроса

2021-02-26 19:45 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
у тебя в answer_params параметрах нет category_id, у тебя вообще не будет ответ никогда сохранен

2021-02-26 19:45 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +<% if  @percent >= 85 %>
что такое 85? почему не 73? без контекста - это просто магическое число.
помести его в модель в константу и обзови понятно.
так же сам этот метод сравнения можно поместить в модель и тут тогда будет что-то типа `@test_passage.success?`

2021-02-26 19:45 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @percent = @test_passage.correct_questions / @test_passage.test.questions.count * 100
подсчет результата можно вынести в метод модели. вдруг тебе где-то еще нужно будет считать, не дублировать же при этом код рассчета? просто вызываешь метод модели `test_passage.result`

2021-02-26 19:45 UTC, BubuntuClu commented on db/migrate/20210225074426_drop_table_user_tests.rb
> +  def up
чтобы не обыло ошибки при попытке откатить эту миграцию, следует добавить `down` метод. можно оставить его просто пустым

2021-02-26 19:45 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    @count = session[:count] + 1
шота тут сложная материя случилась)
такого рода логику не стоит делать на сессиях. сессия просто для хранения какой-то информации, которая обычно статичная. калькуляции не надо туда помещать.
нужно сделать метод в моделе, который будет по текущему вопросу высчитывать сколько уже прошло или сколько осталось.

2021-02-27 05:05 UTC, kokdot commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
есть

2021-02-27 05:28 UTC, kokdot commented on app/views/test_passages/result.html.erb
> +<% if  @percent >= 85 %>
есть

2021-02-27 05:28 UTC, kokdot commented on app/controllers/test_passages_controller.rb
> +    @percent = @test_passage.correct_questions / @test_passage.test.questions.count * 100
есть

2021-02-27 05:29 UTC, kokdot commented on db/migrate/20210225074426_drop_table_user_tests.rb
> +  def up
есть

2021-02-27 05:42 UTC, kokdot commented on app/controllers/test_passages_controller.rb
> +    @count = session[:count] + 1
есть

2021-02-27 06:31 UTC, BubuntuClu approved these changes

2021-02-27 06:31 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      params.require(:answer).permit(:body, :correct, :question_id)
Если ты создаёшь через ассоциацию, то не надо параметр добавлять, он возьмётся из ассоциации. А вот если ты просто делаешь Answer.create то тогда надо параметр передавать

2021-02-27 06:31 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  SUCCESS = 85
Не очень понятно что за успех. Не бойся длинных имен, чем понятней все названо, тем лучше

2021-02-27 07:34 UTC, merged