Lesson 10
kokdot/testguru pull request #9
Opened 2021-02-28 15:47 UTC by kokdot

2021-02-28 18:18 UTC, BubuntuClu requested changes

2021-02-28 18:18 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    session[:url] = request.url
что за url? имя ключа не информативное, вообще не понятно о чем эта сессия

2021-02-28 18:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!
этот метод можно поместить в application_controller вместо того чтобы прописывать в каждом контроллере его вызов

2021-02-28 18:18 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url]
redirect_to session[:хорошее_понятное_название] || root_path

2021-02-28 18:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод уже не нужен. используй просто метод `current_user` вместо `@user`

2021-02-28 18:18 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
ограничения надо дублировать на всех уровнях приложения. 
нужно добавить уникальный индекс в БД

2021-03-01 05:31 UTC, kokdot commented on app/controllers/sessions_controller.rb
> +      redirect_to session[:url]
есть

2021-03-01 05:32 UTC, kokdot commented on app/controllers/application_controller.rb
> +    session[:url] = request.url
есть

2021-03-01 05:53 UTC, kokdot commented on app/controllers/tests_controller.rb
>    def set_user
есть

2021-03-01 06:05 UTC, kokdot commented on app/models/user.rb
> +  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
есть

2021-03-01 06:47 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    session[:user_first_url] = request.url
на мой вкус лучше `requested_url/redirect_url`

2021-03-01 06:55 UTC, merged